In [1]:
import pandas as pd

df = pd.read_csv("police_project.csv")

df

stop_date stop_time  county_name driver_gender  driver_age_raw  \
0      2005-01-02     01:55          NaN             M          1985.0   
1      2005-01-18     08:15          NaN             M          1965.0   
2      2005-01-23     23:15          NaN             M          1972.0   
3      2005-02-20     17:15          NaN             M          1986.0   
4      2005-03-14     10:00          NaN             F          1984.0   
...           ...       ...          ...           ...             ...   
91736  2015-12-31     20:27          NaN             M          1986.0   
91737  2015-12-31     20:35          NaN             F          1982.0   
91738  2015-12-31     20:45          NaN             M          1992.0   
91739  2015-12-31     21:42          NaN             M          1993.0   
91740  2015-12-31     22:46          NaN             M          1959.0   

       driver_age driver_race                   violation_raw  \
0            20.0       White                        Speeding   
1            40.0       White                        Speeding   
2            33.0       White                        Speeding   
3            19.0       White                Call for Service   
4            21.0       White                        Speeding   
...           ...         ...                             ...   
91736        29.0       White                        Speeding   
91737        33.0       White  Equipment/Inspection Violation   
91738        23.0       White         Other Traffic Violation   
91739        22.0       White                        Speeding   
91740        56.0    Hispanic                        Speeding   

              violation  search_conducted search_type   stop_outcome  \
0              Speeding             False         NaN       Citation   
1              Speeding             False         NaN       Citation   
2              Speeding             False         NaN       Citation   
3                 Other             False         NaN  Arrest Driver   
4              Speeding             False         NaN       Citation   
...                 ...               ...         ...            ...   
91736          Speeding             False         NaN        Warning   
91737         Equipment             False         NaN        Warning   
91738  Moving violation             False         NaN        Warning   
91739          Speeding             False         NaN       Citation   
91740          Speeding             False         NaN       Citation   

      is_arrested stop_duration  drugs_related_stop  
0           False      0-15 Min               False  
1           False      0-15 Min               False  
2           False      0-15 Min               False  
3            True     16-30 Min               False  
4           False      0-15 Min               False  
...           ...           ...                 ...  
91736       False      0-15 Min               False  
91737       False      0-15 Min               False  
91738       False      0-15 Min               False  
91739       False      0-15 Min               False  
91740       False      0-15 Min               False  

[91741 rows x 15 columns]

In [2]:
df.stop_outcome.unique()

array(['Citation', 'Arrest Driver', nan, 'N/D', 'Warning',
       'Arrest Passenger', 'No Action'], dtype=object)

In [3]:
df.stop_outcome.value_counts()

Citation            77006
Warning              5294
Arrest Driver        2571
N/D                   590
No Action             589
Arrest Passenger      358
Name: stop_outcome, dtype: int64

In [4]:
df.county_name.unique()

array([nan])

In [5]:
#df2= pd.get_dummies(df, columns=["stop_outcome"])
cat_columns = df.select_dtypes(['object']).columns
cat_columns

Index(['stop_date', 'stop_time', 'driver_gender', 'driver_race',
       'violation_raw', 'violation', 'search_type', 'stop_outcome',
       'is_arrested', 'stop_duration'],
      dtype='object')

In [6]:
df["driver_race"]

0           White
1           White
2           White
3           White
4           White
           ...   
91736       White
91737       White
91738       White
91739       White
91740    Hispanic
Name: driver_race, Length: 91741, dtype: object

In [7]:
#df[cat_columns] = df[cat_columns]
for c in cat_columns:
    df[c] = df[c].astype("category").cat.codes
df

stop_date  stop_time  county_name  driver_gender  driver_age_raw  \
0              0        115          NaN              1          1985.0   
1              1        491          NaN              1          1965.0   
2              2       1391          NaN              1          1972.0   
3              3       1031          NaN              1          1986.0   
4              4        596          NaN              0          1984.0   
...          ...        ...          ...            ...             ...   
91736       3767       1223          NaN              1          1986.0   
91737       3767       1231          NaN              0          1982.0   
91738       3767       1241          NaN              1          1992.0   
91739       3767       1298          NaN              1          1993.0   
91740       3767       1362          NaN              1          1959.0   

       driver_age  driver_race  violation_raw  violation  search_conducted  \
0            20.0            4              8          5             False   
1            40.0            4              8          5             False   
2            33.0            4              8          5             False   
3            19.0            4              1          2             False   
4            21.0            4              8          5             False   
...           ...          ...            ...        ...               ...   
91736        29.0            4              8          5             False   
91737        33.0            4              2          0             False   
91738        23.0            4              4          1             False   
91739        22.0            4              8          5             False   
91740        56.0            2              8          5             False   

       search_type  stop_outcome  is_arrested  stop_duration  \
0               -1             2            0              0   
1               -1             2            0              0   
2               -1             2            0              0   
3               -1             0            1              2   
4               -1             2            0              0   
...            ...           ...          ...            ...   
91736           -1             5            0              0   
91737           -1             5            0              0   
91738           -1             5            0              0   
91739           -1             2            0              0   
91740           -1             2            0              0   

       drugs_related_stop  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
91736               False  
91737               False  
91738               False  
91739               False  
91740               False  

[91741 rows x 15 columns]

In [9]:
df= df.drop("county_name",axis=1)
df

stop_date  stop_time  driver_gender  driver_age_raw  driver_age  \
0              0        115              1          1985.0        20.0   
1              1        491              1          1965.0        40.0   
2              2       1391              1          1972.0        33.0   
3              3       1031              1          1986.0        19.0   
4              4        596              0          1984.0        21.0   
...          ...        ...            ...             ...         ...   
91736       3767       1223              1          1986.0        29.0   
91737       3767       1231              0          1982.0        33.0   
91738       3767       1241              1          1992.0        23.0   
91739       3767       1298              1          1993.0        22.0   
91740       3767       1362              1          1959.0        56.0   

       driver_race  violation_raw  violation  search_conducted  search_type  \
0                4              8          5             False           -1   
1                4              8          5             False           -1   
2                4              8          5             False           -1   
3                4              1          2             False           -1   
4                4              8          5             False           -1   
...            ...            ...        ...               ...          ...   
91736            4              8          5             False           -1   
91737            4              2          0             False           -1   
91738            4              4          1             False           -1   
91739            4              8          5             False           -1   
91740            2              8          5             False           -1   

       stop_outcome  is_arrested  stop_duration  drugs_related_stop  
0                 2            0              0               False  
1                 2            0              0               False  
2                 2            0              0               False  
3                 0            1              2               False  
4                 2            0              0               False  
...             ...          ...            ...                 ...  
91736             5            0              0               False  
91737             5            0              0               False  
91738             5            0              0               False  
91739             2            0              0               False  
91740             2            0              0               False  

[91741 rows x 14 columns]

In [10]:
import torch

In [12]:
from torch.utils.data import Dataset

In [38]:
import numpy as np
class PoliceDataset(Dataset):
    def __init__(self, csv_file, label_column="stop_outcome"):
        df = pd.read_csv(csv_file)
        cat_columns = df.select_dtypes(['object']).columns
        df = df.drop("county_name", axis=1)
        df = df.dropna()
        for c in cat_columns:
            df[c] = df[c].astype("category").cat.codes

        self.features= df.drop("stop_outcome",axis=1).values
        
        
        self.labels = df["stop_outcome"].values
    def __len__(self):
        return len(self.features)
    
    def __getitem__(self,index):
        # return the features and the labels
        return (
            torch.tensor(self.features[index].astype(np.float), dtype=torch.float), 
            torch.tensor(self.labels[index].astype(np.float), dtype=torch.uint8)
        )

In [39]:
my_dataset= PoliceDataset("police_project.csv")
features, labels = my_dataset[0]

In [40]:
features.dtype, labels.dtype

(torch.float32, torch.uint8)

In [41]:
import numpy, sys
numpy.set_printoptions(threshold=sys.maxsize)
print(features)

tensor([0.0000e+00, 6.0000e+01, 1.0000e+00, 1.9790e+03, 2.6000e+01, 4.0000e+00,
        4.0000e+00, 1.0000e+00, 1.0000e+00, 8.0000e+00, 1.0000e+00, 1.0000e+00,
        0.0000e+00])


In [42]:
from torch.utils.data import DataLoader
my_dataloader = DataLoader(my_dataset, batch_size=16)
my_dataloader

In [43]:
f, l = next(iter(my_dataloader))

In [44]:
f.shape

torch.Size([16, 13])

In [45]:
l.shape

torch.Size([16])

In [46]:
from torch import nn

In [47]:
class MyNeuralNet(nn.Module):
    def __init__(self, input_size, num_layers=3,num_classes= 6, width=1000, dropout=0.5):
        super().__init__()
        self.input_size = input_size
        self.num_layers=num_layers
        self.width=width
        self.dropout=dropout
        
        
        layers = [nn.Linear(input_size, width)]
        layers += [
            nn.Sequential(
                nn.Dropout(dropout),
                nn.Linear(width, width),
                nn.ReLU()
            )
            for _ in range(num_layers)
        ]
        
        layers.append(nn.Linear(width, num_classes))

        self.net= nn.Sequential(*layers)
        
    def forward(self, x):
        return self.net(x)

In [61]:
my_net= MyNeuralNet(input_size=13, num_layers=5)
my_net

MyNeuralNet(
  (net): Sequential(
    (0): Linear(in_features=13, out_features=1000, bias=True)
    (1): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1000, out_features=1000, bias=True)
      (2): ReLU()
    )
    (2): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1000, out_features=1000, bias=True)
      (2): ReLU()
    )
    (3): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1000, out_features=1000, bias=True)
      (2): ReLU()
    )
    (4): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1000, out_features=1000, bias=True)
      (2): ReLU()
    )
    (5): Sequential(
      (0): Dropout(p=0.5, inplace=False)
      (1): Linear(in_features=1000, out_features=1000, bias=True)
      (2): ReLU()
    )
    (6): Linear(in_features=1000, out_features=6, bias=True)
  )
)

In [49]:
my_net(f)

tensor([[-21.7725,  53.4821,  -8.1805,  26.7612,  17.7860, -66.2488],
        [ 19.2705,  81.5669,   6.0947,  46.8182,  -2.0619, -32.6895],
        [ -7.1954,  15.1939,  16.0426,  -7.3082, -54.2778,  24.1849],
        [-32.7021, -17.9903,  55.1524,  49.0342, -27.6386, -38.7946],
        [  0.5720,  33.2453,   8.7449,  15.3079, -40.3382,  -0.3061],
        [-58.9604,  15.7776,   2.6764, -17.2375, -47.8776, -17.2930],
        [ -9.7772,  58.2023,   8.4369,  14.8630, -38.5791, -34.9210],
        [  5.5092,  36.2822, -10.0897,  11.1875, -36.3935,  12.6164],
        [ 10.3310,  37.4528,  19.8989,  14.0256, -49.1674, -39.1321],
        [-16.6418,  95.6833,  36.6769,  63.4232, -35.1652, -20.8306],
        [-11.9518,  55.9172, -65.4210,  67.7803, -33.6345, -35.9867],
        [-16.5394,  22.7189,   2.8972,  19.0770,  -1.7294, -25.7304],
        [-42.8321,  46.8963, -33.8353,   1.3698, -44.4666, -22.7748],
        [-16.8583,   2.5758,  -4.0087, -10.5014, -77.3521, -54.2037],
        [-28.4369,  

In [50]:
l.shape

torch.Size([16])

In [51]:
l

tensor([0, 0, 2, 0, 2, 0, 0, 3, 0, 1, 0, 1, 1, 0, 0, 2], dtype=torch.uint8)

In [52]:
#insert training loop here
import torch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
my_net = my_net.to(device)

In [64]:
# import torch.optim
import torch.optim as optim
# instantiate an optimizer
optimizer = optim.Adam(my_net.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

In [65]:
from tqdm import tqdm_notebook as tqdm

# train for n epochs. an epoch is a full iteration through our dataset
num_epochs = 10

# create something to track of accuracy over time
accuracies = []

# loop over epochs
for epoch in tqdm(range(num_epochs), desc="Epoch"):
    
    # track our accuracy
    correct_this_epoch = 0.
    
    # loop over our data loader
    for data, labels in tqdm(my_dataloader, desc="Batch", leave=False):
        data, labels = data.to(device), labels.to(device)
        
        # pass data through model
        outputs = my_net(data)
        # calculate the loss
#         print(outputs.size())
#         print(labels.long().size())
        loss = criterion(outputs, labels.long())
        
        # Use our optimizer to update the network
        # 1: zero_grad our optimizer
        optimizer.zero_grad()
        # 2: run a backward pass
        loss.backward()
        # 3: make a step
        optimizer.step()
        
        _, preds = torch.max(outputs, dim=1)
        correct_this_epoch += torch.sum(preds==labels.data.long())
        
    accuracy_this_epoch = correct_this_epoch.double() / len(my_dataset)
    print(accuracy_this_epoch)
    accuracies.append(accuracy_this_epoch.item())

tensor(0.5850, dtype=torch.float64)


tensor(0.5897, dtype=torch.float64)


tensor(0.5916, dtype=torch.float64)


tensor(0.5929, dtype=torch.float64)


tensor(0.5904, dtype=torch.float64)


tensor(0.5907, dtype=torch.float64)


tensor(0.5988, dtype=torch.float64)


tensor(0.5885, dtype=torch.float64)


tensor(0.5947, dtype=torch.float64)


tensor(0.5919, dtype=torch.float64)

